workflows:
  react-native-android:
    name: Tap Dash Android
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      node: 16.14.2
      npm: 8.5.0
      java: 11
    cache:
      cache_paths:
        - ~/.npm
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Setup Expo and EAS
        script: |
          npm install -g expo-cli
          npm install -g eas-cli
      - name: Prebuild for Android
        script: |
          npx expo prebuild -p android --no-install
      - name: Build debug APK (skip signing)
        script: |
          cd android
          # Build a debug APK which doesn't require signing
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - karem.kamel@gmail.com
